### ISSUE TITLE
PARTUUID vs UUID

### ISSUE THREAD

**Issue by livier** [pigmonkey/cryptshot#7]
I want to use your script, thanks for having doing it ;-)

I want to make backups on a usb-drive, and a meeted a difficulty when connecting it to another usb-port. 

I founded a solution by changing all "uuid" references in the script by "partuuid" witch , in my knowledge, will never change. 

I also change [ echo "Volume $PARTUUID not found." ] by [  echo "$volume not found." ] for a outputa bit more explicit> 

Are you ok with that and do you want to enhance the script with it ?

Another bug-report for another topic to follow ...

**Comment by pigmonkey** [comment]
[The UUID of a disk will not change when it is plugged into different USB ports](https://wiki.archlinux.org/title/Persistent_block_device_naming#by-uuid). It is persistent and unique to the filesystem. It only changes when a partition is reformatted.

You should not have to use PARTUUID, but you may be using an incorrect value as the UUID if it isn't persistent for you.

**Comment by livier** [comment]
Thanks for the link, understood and tested, you are rignht, excuses for the noise.

**Comment by livier** [comment]
@pigmonkey  For the record I understood why I thougt UUID was changing .... 
There is a difference between UUID of the uncryped LUKS partition and the decrypted one ; while the PARTUUID is still the same.

**Comment by pigmonkey** [comment]
That makes sense. If your LUKS partition was inside of a LVM mapper, I don't think it would even have a PARTUUID value.

**Comment by livier** [comment]
I have a LVM mapper as principal disk for the computer, but not for the USB one concerned here !

**Comment by livier** [comment]
Furthermore, the UUID is not the same when the volume is mounted by root or by the user, whereas PARTUUID remains the same.

**Comment by pigmonkey** [comment]
The UUID is assigned by the file system formatter (eg, `mkfs.ext4`). It doesn't have anything to do with the user, or even if the file system is mounted or not. I can plug the same drive into different computers with completely different users and get the same UUID for the file system. I don't know why you would be seeing different values.
